name: Keep Render Alive & Run Cron Jobs

on:
  schedule:
    - cron: "* * * * *" # Runs every minute
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  ping-render:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ vars.BACKEND_URL }}

    steps:
      - name: Run task reminder cron job
        run: curl -X GET "$BACKEND_URL/api/run-cron"
